apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
    env: demo
  name: todo-app
spec:
  type: NodePort
  selector:
    app: flowsheet-simulation
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 9000
